#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

PACKAGE_VERSION=$(cat package.json \
  | grep version \
  | head -1 \
  | awk -F: '{ print $2 }' \
  | sed 's/[",]//g' \
  | sed -e s/^[[:space:]]*//)

git tag -a "v$PACKAGE_VERSION" -m "Version $PACKAGE_VERSION"
git push --tags
