name: Chrome Extension - Build and Publish

on:
  push:
    branches: ['main']

env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}

jobs:
  chrome-extension-build:
    name: Build Extension Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Dependancies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive Chrome Extension Artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.event.pull_request.head.sha }}.zip

  chrome-extension-publish:
    name: Publish Chrome Extension
    runs-on: ubuntu-latest
    needs: chrome-extension-build
    env:
      EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
      CI_GOOGLE_CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID   }}
      CI_GOOGLE_CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}
      CI_GOOGLE_REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}

    steps:
      - name: Setup Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: 'npm'

      - name: Download Extension Artifact
        uses: actions/download-artifact@v2
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install WebStore CLI
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload Extension to Webstore
        run: |-
          chrome-webstore-upload upload \\
            --source chrome-extension-${{ github.event.pull_request.head.sha }}.zip \\
            --extension-id ${{ env.EXTENSION_ID }} \\
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \\
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \\
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
